name: build-master

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Login to Docker hub Registry
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Grant execute permission for gradlew
      working-directory: ./backend
      run: chmod +x gradlew
      
    - name: Build backend app and create docker
      working-directory: ./backend
      run: |
          export buildVersion=stage
          ./gradlew jib

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to Docker hub Registry
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build frontend app
      working-directory: ./frontend
      run: |
        yarn install
        yarn build

    - name: Build frontend docker
      working-directory: ./frontend
      run: |
        docker build -t mikenieto/frontend:stage .
        docker push mikenieto/frontend:stage


  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: manusa/actions-setup-minikube@v1.0.0
      with:
          minikube version: 'v1.5.2'
          kubernetes version: 'v1.16.2'
    - name: Interact with the cluster
      working-directory: ./frontend/k8s
      run: |
        sudo apt-get update && sudo apt-get install socat
        kubectl apply -f Deployment.yaml
        kubectl wait --for=condition=Ready pod/$(kubectl get pod -l app=frontend -o jsonpath={.items[0].metadata.name})
        nohup kubectl port-forward service/frontend-service 9090:80 &
        kubectl get pods -l app=frontend
        sleep 5
        curl http://localhost:9090
    - name: Run cypress test
      working-directory: ./frontend
      run: |
        kubectl get pods -l app=frontend
        curl http://localhost:9090
        yarn install
        yarn cypress:run
