name: build-master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Login to Docker hub Registry
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Grant execute permission for gradlew
      working-directory: ./backend
      run: chmod +x gradlew
      
    - name: Build backend app and create docker
      working-directory: ./backend
      run: |
          export buildVersion=stage
          ./gradlew jib

    - name: Build frontend app
      working-directory: ./frontend
      run: |
        yarn install
        yarn build

    - name: Build frontend docker
      working-directory: ./frontend
      run: |
        docker build -t mikenieto/frontend:stage .
        docker push mikenieto/frontend:stage
